#pragma once

#ifndef MENUID_H
#define MENUID_H

enum MenuID
{
	//File menu
	ID_FILE_INSTRUMENT_SELECTION = 1,
	ID_FILE_SPOTFIELD_IMAGE = 2,
	ID_FILE_MEASUREMENT_DATA = 3,
	ID_FILE_CENTROID_DATA = 4,
	ID_FILE_POWER_DISTRIBUTION_DATA = 5,
	// Setup menu
	ID_SETUP_CAMERA_SETTINGS = 6,
	ID_SETUP_MLA_SETTINGS = 7,
	ID_SETUP_MISCELLANEOUS_SETTINGS = 8,
	// Measurement menu
	ID_MEASUREMENT_START = 9,
	ID_MEASUREMENT_STOP = 10,
	ID_MEASUREMENT_PREFERENCES = 11,
	ID_MEASUREMENT_DATA = 14,
	// Calibration menu
	ID_CALIBRATION_CALIBRATE_CAMERA = 12,
	// Display menu
	ID_DISPLAY_SETTINGS = 13,
};


#endif 
