.TH "CameraConfig" 3 "PROJH402 - Image Acquisition with Plenoptic Camera" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraConfig \- This model class contains all the information about the camera configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CameraConfig\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraConfig\fP (int cameraResolution, int exposureTime, int gain, int noiseCutLevel, int blackLevel, int nbImageReadings)"
.br
.ti -1c
.RI "int \fBgetCameraResolution\fP ()"
.br
.ti -1c
.RI "ViReal64 * \fBgetExposureTime\fP ()"
.br
.ti -1c
.RI "ViReal64 * \fBgetGain\fP ()"
.br
.ti -1c
.RI "int \fBgetNoiseCutLevel\fP ()"
.br
.ti -1c
.RI "int \fBgetBlackLevel\fP ()"
.br
.ti -1c
.RI "int \fBgetNbImageReadings\fP ()"
.br
.ti -1c
.RI "void \fBsetCameraConfig\fP (int cameraResolution, int exposureTime, int gain, int noiseCutLevel, int blackLevel, int nbImageReadings)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This model class contains all the information about the camera configuration\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJH402 - Image Acquisition with Plenoptic Camera from the source code\&.
