.TH "Message" 3 "PROJH402 - Image Acquisition with Plenoptic Camera" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP (int code, std::string message)"
.br
.ti -1c
.RI "int \fBgetCode\fP ()"
.br
.ti -1c
.RI "std::string \fBgetMessage\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJH402 - Image Acquisition with Plenoptic Camera from the source code\&.
