.TH "Mla" 3 "PROJH402 - Image Acquisition with Plenoptic Camera" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mla \- This model class is used to store the information of the MLA\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mla\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ViInt32 * \fBgetMlaCount\fP ()"
.br
.ti -1c
.RI "ViSession \fBgetHandle\fP ()"
.br
.ti -1c
.RI "bool \fBisInitialized\fP ()"
.br
.ti -1c
.RI "void \fBsetInitialized\fP (bool is_initialized)"
.br
.ti -1c
.RI "void \fBsetHandle\fP (ViSession handle)"
.br
.ti -1c
.RI "void \fBsetMlaInfo\fP (ViChar *mla_name, ViReal64 cam_pitchm, ViReal64 lenslet_pitchm, ViReal64 spot_offset_x, ViReal64 spot_offset_y, ViReal64 lenslet_fm, ViReal64 grd_corr_0, ViReal64 grd_corr_45)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This model class is used to store the information of the MLA\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJH402 - Image Acquisition with Plenoptic Camera from the source code\&.
