.TH "MyApp" 3 "PROJH402 - Image Acquisition with Plenoptic Camera" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJH402 - Image Acquisition with Plenoptic Camera from the source code\&.
