.TH "MyApp" 3 "PROJH402 - Image Acquisition with Plenoptic Camera" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyApp \- This class is the main class of the application responsible to manage all the application controllers and views\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MyApp\&.h>\fP
.PP
Inherits wxApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.ti -1c
.RI "virtual int \fBOnExit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is the main class of the application responsible to manage all the application controllers and views\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJH402 - Image Acquisition with Plenoptic Camera from the source code\&.
